apotek-jaya/apotekjaya/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('employees/', include('employees.urls')),
    path('departments/', include('departments.urls')),
    # path('permission/', include('permission.urls')),
    path('benefits/', include('benefits.urls')),
    path('salaries/', include('salaries.urls')),
    path('overtimes/', include('overtimes.urls')),
    path('presences/', include('presences.urls')),
    path('leaves/', include('leaves.urls')),
    path('reports/', include('reports.urls')),
    path('settings/', include('settings.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'main_app.views.error_404_view'
handler500 = 'main_app.views.error_500_view'

apotek-jaya/leaves/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

app_name = 'leaves'
urlpatterns = [
    path('',views.LeavesView.as_view(), name='leaves'),
    path('fetch-leaves/',views.ListLeavesView.as_view(), name='fetch-leaves'),
    path('create/',views.CreateLeavesView.as_view(), name='create-leaves'),
    path('detail/<str:leave_uuid>',views.DetailLeavesView.as_view(), name='detail-leaves'),
    path('delete/<str:leave_uuid>',views.DeleteLeavesView.as_view(), name='delete-leaves'),
    path('update/<str:leave_uuid>',views.UpdateLeavesView.as_view(), name='update-leaves'),
    
    # path('balance/',views.LeavesBalancesView.as_view(), name='leaves-balances'),
    # path('balance/add-leaves-balances/',views.AddLeavesBalancesView.as_view(), name='add-leaves-balances'),
    # path('balance/fetch-leaves-balances/',views.ListLeavesBalancesView.as_view(), name='fetch-leaves-balances'),
    # path('balance/create/',views.CreateLeavesBalancesView.as_view(), name='create-leaves-balances'),
    # path('balance/detail/<str:leave_balance_uuid>',views.DetailLeavesBalancesView.as_view(), name='detail-leaves-balances'),
    # path('balance/delete/<str:leave_balance_uuid>',views.DeleteLeavesBalancesView.as_view(), name='delete-leaves-balances'),
    # path('balance/update/<str:leave_balance_uuid>',views.UpdateLeavesBalancesView.as_view(), name='update-leaves-balances'),
]
urlpatterns += staticfiles_urlpatterns()

apotek-jaya/permission/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

app_name = 'permission'
urlpatterns = [
    path('',views.PermissionView.as_view(), name='permission'),
    path('list-permission/',views.ListPermissionView.as_view(), name='list-permission'),
    path('create/',views.CreatePermissionView.as_view(), name='create-permission'),
    path('detail/<str:employee_uuid>',views.DetailPermissionView.as_view(), name='detail-permission'),
    path('update/<str:employee_uuid>',views.UpdatePermissionView.as_view(), name='update-permission'),
    path('delete/<str:employee_uuid>',views.DeletePermissionView.as_view(), name='delete-permission'),

    path('group/',views.PermissionGroupView.as_view(), name='permission-group'),
    path('group/list-permission-group/',views.ListPermissionGroupView.as_view(), name='list-permission-group'),
    path('group/create',views.CreatePermissionGroupView.as_view(), name='create-permission-group'),
    path('group/detail/<str:group_id>',views.DetailPermissionGroupView.as_view(), name='detail-permission-group'),
    path('group/update/<str:group_id>',views.UpdatePermissionGroupView.as_view(), name='update-permission-group'),
    path('group/delete/<str:group_id>',views.DeletePermissionGroupView.as_view(), name='delete-permission-group'),

]
urlpatterns += staticfiles_urlpatterns()

apotek-jaya/permission/models.py
from django.db import models

from django.contrib.auth.models import User, Group

class AuthGroupExtended(models.Model):
    auth_group_id = models.OneToOneField(Group, 
                                     on_delete=models.CASCADE,
                                     related_name='auth_group_id',
                                     db_column='auth_group_id')

    created_at = models.DateTimeField()
    created_by = models.ForeignKey(User,
                                      on_delete=models.CASCADE, 
                                      related_name='created_by_group',
                                      db_column='created_by',
                                      blank=True)

    updated_at = models.DateTimeField(null=True, blank=True, default=None)
    updated_by = models.ForeignKey(User,
                                      on_delete=models.CASCADE, 
                                      related_name='updated_by_group',
                                      db_column='updated_by',
                                      null=True, 
                                      blank=True)

    status = models.IntegerField(default=1)

    def __str__(self):
        return str(self.auth_group_id.name)

    class Meta:
        db_table = 'auth_group_extended'
        verbose_name_plural = 'Auth Group Extended'
        default_permissions = ()
        permissions = (
            ("create_auth_group_extended", "Create Auth Group Extended"),
            ("read_auth_group_extended", "Read Auth Group Extended"),
            ("update_auth_group_extended", "Update Auth Group Extended"),
            ("delete_auth_group_extended", "Delete Auth Group Extended"),
        )

apotek-jaya/permission/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic import View
from django.contrib import messages
from django.contrib.auth.models import User, Permission, Group
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.template.loader import render_to_string
from departments.models import DepartmentMembers

from .forms import PermissionForm, PermissionGroupForm
from employees.models import Employees

class CreatePermissionView(LoginRequiredMixin, PermissionRequiredMixin, View):
    login_url = '/login/'
    permission_required = ['auth.view_permission', 'auth.add_permission']

    def handle_no_permission(self):
        if self.request.user.is_authenticated:
            response = {
                'success': False,
                'errors': [],
                'modal_messages':[],
                'toast_message':'You Are Not Authorized',
                'is_close_modal':False,

            }

            return JsonResponse(response)
        
        return redirect(reverse_lazy('main_app:login'))
    
    def get(self, request):
        permission_form = PermissionForm(is_creating=True)
        context = {
            'success':True,
            'mode':'create',
            'modal_title':'create permission',
            'permission_form':permission_form,
            'uq':{
                'create_link':str(reverse_lazy('permission:create-permission')),
            }
        }
        
        form = render_to_string('permission/includes/form.html', context, request=request)
        response = {
            'success':True,
            'form': form
            
        }
        return JsonResponse(response)
    
    def post(self, request):
        permission_form = PermissionForm(request.POST or None)

        if permission_form.is_valid():
            try:
                employees = permission_form.cleaned_data['employees']
                user = get_object_or_404(User, id=employees.auth_user_id.id)

                permissions = permission_form.cleaned_data['permissions']
                user_perms = [ Permission.objects.get(id=p.id) for p in permissions ]
                
                user.user_permissions.set(user_perms)
                
            except Exception as e:
                response = {
                    'success': False, 
                    'errors': [], 
                    'modal_messages':[],
                    'toast_message':'We\'re sorry, but something went wrong on our end. Please try again later.',
                    'is_close_modal':False,
                }

                return JsonResponse(response)

            response = {
                'success': True, 
                'toast_message':'Permission Added Successfuly',
                'is_close_modal':True
            }

            return JsonResponse(response)
    
        else:
            messages.error(request,'Please Correct The Errors Below')
            modal_messages = []
            for message in messages.get_messages(request):
                modal_messages.append({
                    'message':str(message),
                    'tags': message.tags
                })

            errors = {}
            for field, error_list in permission_form.errors.items():
                errors[field] = error_list

            response = {
                'success': False, 
                'errors': errors, 
                'modal_messages':modal_messages,
                'toast_message':'Please review the form and correct any errors before resubmitting',
                'is_close_modal':False
            }

            return JsonResponse(response)
class UpdatePermissionView(LoginRequiredMixin, PermissionRequiredMixin, View):
    login_url = '/login/'
    permission_required = ['auth.view_permission', 'auth.change_permission']

    def handle_no_permission(self):
        if self.request.user.is_authenticated:
            response = {
                'success': False,
                'errors': [],
                'modal_messages':[],
                'toast_message':'You Are Not Authorized',
                'is_close_modal':False,

            }

            return JsonResponse(response)
        
        return redirect(reverse_lazy('main_app:login'))

    def get(self, request, employee_uuid):
        permission_data = []
        employee = Employees.objects.filter(hash_uuid=employee_uuid)[0]
        employee_permissions = employee.auth_user_id.user_permissions.all()
        employee_permissions = [ x.id for x in employee_permissions ]
        
        initial_data = {
            'employees':[ employee.id ],
            'permissions':employee_permissions,
        }

        permission_form = PermissionForm(initial=initial_data)

        context = {
            'mode':'update',
            'permission_form':permission_form,
            'modal_title':'update permission',
            'uq':{
                'hash':employee_uuid,
                'update_link':str(reverse_lazy('permission:update-permission', args=["@@"])),
            }
        }
        
        form = render_to_string('permission/includes/form.html', context, request=request)

        response = {
            'success':True,
            'form': form,
            'permission_data':permission_data,
            'is_view_only': True,
        }

        return JsonResponse(response)

    def post(self, request, employee_uuid):
        permission_form = PermissionForm(request.POST or None, is_updating=True)

        if permission_form.is_valid():
            try:
                employees = permission_form.cleaned_data['employees']
                user = get_object_or_404(User, id=employees.auth_user_id.id)

                permissions = permission_form.cleaned_data['permissions']
                added_perms = [ Permission.objects.get(id=p.id) for p in permissions ]

                old_perms = user.user_permissions.all()
                
                removed_perms = []

                for p in old_perms:
                    try: added_perms.remove(p)
                    except: removed_perms.append(p)

                if added_perms:
                    user.user_permissions.add(*added_perms)

                if removed_perms:
                    user.user_permissions.remove(*removed_perms)
                
            except Exception as e:
                response = {
                    'success': False, 
                    'errors': [], 
                    'modal_messages':[],
                    'toast_message':'We\'re sorry, but something went wrong on our end. Please try again later.',
                    'is_close_modal':False,
                }

                return JsonResponse(response)

            response = {
                'success': True, 
                'toast_message':'Permission Added Successfuly',
                'is_close_modal':True
            }

            return JsonResponse(response)
    
        else:
            messages.error(request,'Please Correct The Errors Below')
            modal_messages = []
            for message in messages.get_messages(request):
                modal_messages.append({
                    'message':str(message),
                    'tags': message.tags
                })

            errors = {}
            for field, error_list in permission_form.errors.items():
                errors[field] = error_list

            response = {
                'success': False, 
                'errors': errors, 
                'modal_messages':modal_messages,
                'toast_message':'Please review the form and correct any errors before resubmitting',
                'is_close_modal':False
            }

            return JsonResponse(response)

class DetailPermissionView(LoginRequiredMixin, PermissionRequiredMixin, View):
    login_url = '/login/'
    permission_required = ['auth.view_permission']

    def handle_no_permission(self):
        if self.request.user.is_authenticated:
            response = {
                'success': False,
                'errors': [],
                'modal_messages':[],
                'toast_message':'You Are Not Authorized',
                'is_close_modal':False,
            }

            return JsonResponse(response)
        
    def get(self, request, employee_uuid):
        permission_data = []
        employee = Employees.objects.filter(hash_uuid=employee_uuid)[0]
        employee_permissions = employee.auth_user_id.user_permissions.all()
        employee_permissions = [ x.id for x in employee_permissions ]
        
        initial_data = {
            'employees':[ employee.id ],
            'permissions':employee_permissions,
        }

        permission_form = PermissionForm(initial=initial_data)

        for key in permission_form.fields:
            permission_form.fields[key].widget.attrs['disabled'] = True
            permission_form.fields[key].widget.attrs['placeholder'] = ''

        context = {
            'mode':'view',
            'permission_form':permission_form,
            'modal_title':'view permission',
        }
        
        form = render_to_string('permission/includes/form.html', context, request=request)

        response = {
            'success':True,
            'form': form,
            'permission_data':permission_data,
            'is_view_only': True,
        }

        return JsonResponse(response)

    def post(self, request):
        if self.request.user.is_authenticated:
            return redirect(reverse_lazy('main_app:home'))

        return redirect(reverse_lazy('main_app:login'))

class DeletePermissionView(LoginRequiredMixin, PermissionRequiredMixin, View):
    login_url = '/login/'
    permission_required = ['auth.view_permission', 'auth.delete_permission']

    def handle_no_permission(self):
        if self.request.user.is_authenticated:

apotek-jaya/permission/templates/permission/permission.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{title}}
{% endblock title %}

{% block script_css %}
<link rel="stylesheet" href="https://unpkg.com/@jarstone/dselect/dist/css/dselect.css">
<script src="https://unpkg.com/@jarstone/dselect/dist/js/dselect.js"></script>
<link rel="stylesheet" href="{% static 'permission/permission.css' %}">
{% endblock script_css %}

{% block content %}
{% include 'includes/navbar.html' %}
{% include 'includes/sidebar.html' %}

<div class="container-fluid my-1" style="width: 90%;">
    
    {% include 'permission/includes/permission_modal.html' %}

    <div class="row">
        <div class="col-md-2"><h3>Permission</h3></div>

            {% if perms.auth.add_permission %}
                <div class="col-md-1 mt-1">
                    <svg xmlns="http://www.w3.org/2000/svg" 
                            width="26" height="26" fill="green" 
                            class="bi bi-plus-square-fill" viewBox="0 0 16 16" role="button" 
                            data-link="{% url 'permission:create-permission' %}" id="add-permission">
                        <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm6.5 4.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3a.5.5 0 0 1 1 0z" />
                    </svg>
                    &nbsp;
                    <svg xmlns="http://www.w3.org/2000/svg" 
                            width="26" height="26" fill="green" 
                            class="bi bi-file-earmark-excel-fill" viewBox="0 0 16 16" role="button" 
                            id="import-permission">
                        <path d="M9.293 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.707A1 1 0 0 0 13.707 4L10 .293A1 1 0 0 0 9.293 0zM9.5 3.5v-2l3 3h-2a1 1 0 0 1-1-1zM5.884 6.68 8 9.219l2.116-2.54a.5.5 0 1 1 .768.641L8.651 10l2.233 2.68a.5.5 0 0 1-.768.64L8 10.781l-2.116 2.54a.5.5 0 0 1-.768-.641L7.349 10 5.116 7.32a.5.5 0 1 1 .768-.64z" />
                    </svg>
                </div>
            {% endif %}

    </div>
    <hr class="mt-0 mb-4">
    
    {% csrf_token %}

    {% include 'permission/includes/permission_table.html' %}

    <script src="{% static 'permission/permission.js' %}" defer></script>
</div>
{% endblock content %}

apotek-jaya/permission/templates/permission/permission_group.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{title}}
{% endblock title %}

{% block script_css %}
<link rel="stylesheet" href="https://unpkg.com/@jarstone/dselect/dist/css/dselect.css">
<script src="https://unpkg.com/@jarstone/dselect/dist/js/dselect.js"></script>
<link rel="stylesheet" href="{% static 'permission/permission_group.css' %}">
{% endblock script_css %}

{% block content %}
{% include 'includes/navbar.html' %}
{% include 'includes/sidebar.html' %}

<div class="container-fluid my-1" style="width: 90%;">
    
    {% include 'permission/includes/permission_group_modal.html' %}

    <div class="row">
        <div class="col-md-2"><h3>Permission Group</h3></div>

            {% if perms.auth.add_group %}
                <div class="col-md-1 mt-1">
                    <svg xmlns="http://www.w3.org/2000/svg" 
                            width="26" height="26" fill="green" 
                            class="bi bi-plus-square-fill" viewBox="0 0 16 16" role="button" 
                            data-link="{% url 'permission:create-permission-group' %}" id="add-permission-group">
                        <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm6.5 4.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3a.5.5 0 0 1 1 0z" />
                    </svg>
                    &nbsp;
                    <svg xmlns="http://www.w3.org/2000/svg" 
                            width="26" height="26" fill="green" 
                            class="bi bi-file-earmark-excel-fill" viewBox="0 0 16 16" role="button" 
                            id="import-permission-group">
                        <path d="M9.293 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.707A1 1 0 0 0 13.707 4L10 .293A1 1 0 0 0 9.293 0zM9.5 3.5v-2l3 3h-2a1 1 0 0 1-1-1zM5.884 6.68 8 9.219l2.116-2.54a.5.5 0 1 1 .768.641L8.651 10l2.233 2.68a.5.5 0 0 1-.768.64L8 10.781l-2.116 2.54a.5.5 0 0 1-.768-.641L7.349 10 5.116 7.32a.5.5 0 1 1 .768-.64z" />
                    </svg>
                </div>
            {% endif %}
            
    </div>
    <hr class="mt-0 mb-4">
    
    {% csrf_token %}

    {% include 'permission/includes/permission_group_table.html' %}

    <script src="{% static 'permission/permission_group.js' %}" defer></script>
</div>
{% endblock content %}